### ISSUE TITLE
NFC bug in MIUI 14

### ISSUE THREAD

**Issue by white44water** [AndroPlus-org/magisk-module-assistant#1]
MIUI 14 mixfold2
when [magisk-module-assistant] active
NFC cannot use and open

**Comment by AndroPlus-org** [comment]
Maybe this is Magisk's compatibility problem, as replacing the files (or even without changes inside the file) in /system corrupt the NFC.

**Comment by AndroPlus-org** [comment]
Added workaround in cn2global module.
https://github.com/AndroPlus-org/magisk-module-miui-cn2global/commit/502da49e786d088369ee1fea822df898c38eeef7
